### ISSUE TITLE
Add support getting state at a specific block

### ISSUE THREAD

**Issue by mckrava** [galacticcouncil/HydraDX-js#17]
We need support specific blocks queries for some queries. User should be able make query with specifying block hash and get info exactly for this block.

For example, fetching assets list at specific bloc (in specific point of time, e.g. https://polkadot.js.org/docs/api/start/api.query.other/#state-at-a-specific-block).

For now, we need add/update such queries as:
- [ ] `getAssetList`
- [ ] `getPoolAssetsAmounts`
- [ ] `getTokenAmount`
- [ ] `getAccountBalances`
- [ ] `getMarketcap`

I think, we can just add additional optional parameter to each of these function, for specifying block hash. If it's empty - return data from latest block, if existing - return data for mentioned block. Any other proposals?

**Comment by jak-pan** [comment]
Grooming. Is this something we'll ever do?
